### ISSUE TITLE
Error using neovim 0.6.1

### ISSUE THREAD

**Issue by JavaHello** [NiYanhhhhh/lighttree-java#1]
E5108: Error executing lua ...llar/neovim/0.6.1/share/nvim/runtime/lua/vim/lsp/rpc.lua:349: Cannot serialise boolean: table key must be a number or string
stack traceback:
        [C]: in function 'encode'
        ...llar/neovim/0.6.1/share/nvim/runtime/lua/vim/lsp/rpc.lua:349: in function 'encode_and_send'
        ...llar/neovim/0.6.1/share/nvim/runtime/lua/vim/lsp/rpc.lua:397: in function 'request'
        ...w/Cellar/neovim/0.6.1/share/nvim/runtime/lua/vim/lsp.lua:963: in function 'request'
        ...w/Cellar/neovim/0.6.1/share/nvim/runtime/lua/vim/lsp.lua:1422: in function 'fn'
        ...w/Cellar/neovim/0.6.1/share/nvim/runtime/lua/vim/lsp.lua:164: in function 'for_each_buffer_client'
        ...w/Cellar/neovim/0.6.1/share/nvim/runtime/lua/vim/lsp.lua:1421: in function 'buf_request'
        ...w/Cellar/neovim/0.6.1/share/nvim/runtime/lua/vim/lsp.lua:1476: in function 'buf_request_all'
        ...w/Cellar/neovim/0.6.1/share/nvim/runtime/lua/vim/lsp.lua:1499: in function 'buf_request_sync'
        ...lighttree-java/lua/nvim-java-dependency/sync_command.lua:24: in function 'execute_command'
        ...lighttree-java/lua/nvim-java-dependency/sync_command.lua:61: in function 'get_package_data'
        [string "luaeval()"]:1: in main chunk

**Comment by NiYanhhhhh** [comment]
I'm sorry, this project won't update any more. I'm preparing to write a totally new one using lua.

**Comment by NiYanhhhhh** [comment]
@JavaHello Fixed, You can try it again.

**Comment by JavaHello** [comment]
Thank you
